#!/bin/sh
#
# Starts domotica-engine.
#

DOMOTICA_ENGINE_PIDFILE="/var/run/domotica-engine.pid"
DOMOTICA_ENGINE_ARGS="-D"

# export TZ for local time calculations
export TZ=$(cat /etc/timezone)

start() {
	printf "Starting domotica-engine: "
	umask 077

	start-stop-daemon -v -S -q -p $DOMOTICA_ENGINE_PIDFILE --exec /usr/sbin/domotica-engine -- $DOMOTICA_ENGINE_ARGS
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	printf "Stopping domotica-engine: "
	start-stop-daemon -K -q -p $DOMOTICA_ENGINE_PIDFILE
	[ $? = 0 ] && echo "OK" || echo "FAIL"
}
restart() {
	stop
	start
}

case "$1" in
  start)
  	start
	;;
  stop)
  	stop
	;;
  restart|reload)
  	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?
